name: Pull Request 

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for ticket
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ticketLink: 'https://jira.segurosbolivar.com/projects/CVC/issues/CVC-%ticketNumber%'
          ticketPrefix: 'CVC-'
          titleRegex: '^CVC-(?<ticketNumber>\d+)'
      
          bodyRegex: 'CVC-(?<ticketNumber>\d+)'
          bodyURLRegex: 'http(s?):\/\/(:jira.segurosbolivar.com)(\/CVC/issues)\/(CVC\-)(?<ticketNumber>\d+)'


  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: new-feature,breaking-change,bug-fix,docs-update,minor-update
          repo_token: ${{ secrets.GITHUB_TOKEN }}
